"""
Django settings for bikeshop project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from pathlib import Path
import os
from dotenv import load_dotenv

# Завантажити .env файл
load_dotenv()


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-^12uqqymo)o)hlvg!-*u3s81dh(@^65yv4)^$85-wg3zbu_%t('  # ЗАБЕЗПЕЧ ПРОТЕКЦІЮ В ПРОДАКШНІ!

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True  # Постав False у продакшн

ALLOWED_HOSTS = []  # Додай доменні імена в продакшн, наприклад ['yourdomain.com']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'shop.apps.ShopConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'bikeshop.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # Якщо хочеш додати загальні шаблони поза додатками, додай тут папку:
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',  # потрібно для auth
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'bikeshop.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        # Можна додати параметр 'OPTIONS': {'min_length': 8} для мінімальної довжини
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'uk-ua'  # Українська мова

TIME_ZONE = 'Europe/Kiev'  # Можна замінити на 'Europe/Kyiv' (правильна транслітерація)

USE_I18N = True
USE_L10N = True  # В Django 5.1 це застаріло, але можна залишити
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]  # папка для статики під час розробки

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  # для команди collectstatic (продакшн)


# Media files (завантажені користувачами файли)

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Налаштування авторизації/редиректів

LOGIN_REDIRECT_URL = 'shop:bike_list'  # Куди після логіну
LOGOUT_REDIRECT_URL = 'shop:home'     # Куди після логауту
LOGIN_URL = 'login'                   # URL логіну (зазвичай 'login' — якщо не namespace)


# Налаштування Email (для відправки листів через SMTP)

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

EMAIL_HOST_USER = 'nemurkadenus@gmail.com'


EMAIL_HOST_PASSWORD = 'bkjdxnpcrkwkvbhn'

DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
